android_library(
    name = "my_search_view",
    custom_package = "io.github.izzyleung",
    srcs = glob(["src/main/java/**/*.java"]),
    manifest = "src/main/AndroidManifest.xml",
    resource_files = glob(["src/main/res/**"]),
    visibility = ["//android/widgets:__pkg__"],
)
